# Generated by Django 3.2.16 on 2023-04-15 12:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_type', models.CharField(max_length=128)),
                ('id_card_nr', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('photo', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Forwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('nr_of_policy', models.CharField(max_length=255)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField()),
                ('insurance_value', models.FloatField()),
                ('is_actual', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_registration', django_countries.fields.CountryField(max_length=2)),
                ('registration_number', models.CharField(max_length=15, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('vin_nr', models.CharField(max_length=17)),
                ('begin_MOT', models.DateField()),
                ('expire_MOT', models.DateField()),
                ('insurance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_registration', models.CharField(max_length=128)),
                ('registration_number', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('vin_nr', models.CharField(max_length=17)),
                ('insurance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nr_of_freight', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loading_address_company_name', models.CharField(max_length=255)),
                ('loading_address_company_address_street', models.CharField(max_length=255)),
                ('loading_address_company_address_local_nr', models.CharField(max_length=255)),
                ('loading_address_company_address_postal_code', models.CharField(max_length=255)),
                ('loading_address_company_address_city', models.CharField(max_length=255)),
                ('loading_address_company_address_country', models.CharField(max_length=255)),
                ('unloading_address_company_name', models.CharField(max_length=255)),
                ('unloading_address_company_address_street', models.CharField(max_length=255)),
                ('unloading_address_company_address_local_nr', models.CharField(max_length=255)),
                ('unloading_address_company_address_postal_code', models.CharField(max_length=255)),
                ('unloading_address_company_address_city', models.CharField(max_length=255)),
                ('unloading_address_company_address_country', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcana_app.driver')),
                ('forwarding', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.forwarding')),
                ('insurance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.insurance')),
                ('trailer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.trailer')),
                ('truck', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcana_app.truck')),
            ],
        ),
    ]
